### ISSUE TITLE
Dirty directory upon pulling from repo

### ISSUE THREAD

**Issue by ruchern** [github-cygwin/android_kernel_samsung_apq8084#1]
Hi,

I have no idea what is going on here, but after I clone the repository, I get this dirty directory of linux files that seemed to have been modified despite me not touching anything.

Any clue to this?

**Comment by github-cygwin** [comment]
What do you mean by "linux files"?

git does not handle a timestamp change as modification.  It does, however, handle a change in permissions or a change of line endings (LF vs. CRLF) as modification.  Is it possible that you run
git clone on Windows?  If so, what git do you use?   The preferred one would be git from the Cygwin distro (https://cygwin.com) inside a directory using POSIX permissions.
If you run git clone on Linux, I have no idea what the actual problem is, sorry.  I guess I'd need a lot more detail then.

Corinna

**Comment by ruchern** [comment]
No. I do not use Windows. I ran on both MacOS and Linux. I'll attach a screenshot.
<img width="570" alt="screen shot 2017-03-08 at 7 52 18 am" src="https://cloud.githubusercontent.com/assets/10343662/23683491/35a6ff0e-03d4-11e7-8f92-41cdaa71a7db.png">

**Comment by github-cygwin** [comment]
And what are the supposed modifications?  Any clue there?

Corinna

**Comment by ruchern** [comment]
```
On branch cm-14.1
Your branch is up-to-date with 'origin/cm-14.1'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   include/uapi/linux/netfilter/xt_CONNMARK.h
	modified:   include/uapi/linux/netfilter/xt_DSCP.h
	modified:   include/uapi/linux/netfilter/xt_MARK.h
	modified:   include/uapi/linux/netfilter/xt_RATEEST.h
	modified:   include/uapi/linux/netfilter/xt_TCPMSS.h
	modified:   include/uapi/linux/netfilter_ipv4/ipt_ECN.h
	modified:   include/uapi/linux/netfilter_ipv4/ipt_TTL.h
	modified:   include/uapi/linux/netfilter_ipv6/ip6t_HL.h
	modified:   net/netfilter/xt_dscp.c
	modified:   net/netfilter/xt_hl.c
	modified:   net/netfilter/xt_rateest.c
	modified:   net/netfilter/xt_tcpmss.c

no changes added to commit (use "git add" and/or "git commit -a")
```

```
diff --git a/include/uapi/linux/netfilter/xt_CONNMARK.h b/include/uapi/linux/netfilter/xt_CONNMARK.h
index 2f2e48e..efc17a8 100644
--- a/include/uapi/linux/netfilter/xt_CONNMARK.h
+++ b/include/uapi/linux/netfilter/xt_CONNMARK.h
@@ -1,6 +1,31 @@
-#ifndef _XT_CONNMARK_H_target
-#define _XT_CONNMARK_H_target
+#ifndef _XT_CONNMARK_H
+#define _XT_CONNMARK_H
 
-#include <linux/netfilter/xt_connmark.h>
+#include <linux/types.h>
 
-#endif /*_XT_CONNMARK_H_target*/
+/* Copyright (C) 2002,2004 MARA Systems AB <http://www.marasystems.com>
+ * by Henrik Nordstrom <hno@marasystems.com>
+ *
+ * This program is free software; you can redistribute it and/or modify
+ * it under the terms of the GNU General Public License as published by
+ * the Free Software Foundation; either version 2 of the License, or
+ * (at your option) any later version.
+ */
+
+enum {
+       XT_CONNMARK_SET = 0,
+       XT_CONNMARK_SAVE,
+       XT_CONNMARK_RESTORE
+};
+
+struct xt_connmark_tginfo1 {
+       __u32 ctmark, ctmask, nfmask;
+       __u8 mode;
+};
+
+struct xt_connmark_mtinfo1 {
+       __u32 mark, mask;
+       __u8 invert;
+};
+
+#endif /*_XT_CONNMARK_H*/
```

One of the few files with `git diff`

**Comment by github-cygwin** [comment]
On Mar  8 03:26, Chong Ru Chern wrote:
> ```
> On branch cm-14.1
> Your branch is up-to-date with 'origin/cm-14.1'.
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   include/uapi/linux/netfilter/xt_CONNMARK.h
> 	modified:   include/uapi/linux/netfilter/xt_DSCP.h
> 	modified:   include/uapi/linux/netfilter/xt_MARK.h
> 	modified:   include/uapi/linux/netfilter/xt_RATEEST.h
> 	modified:   include/uapi/linux/netfilter/xt_TCPMSS.h
> 	modified:   include/uapi/linux/netfilter_ipv4/ipt_ECN.h
> 	modified:   include/uapi/linux/netfilter_ipv4/ipt_TTL.h
> 	modified:   include/uapi/linux/netfilter_ipv6/ip6t_HL.h
> 	modified:   net/netfilter/xt_dscp.c
> 	modified:   net/netfilter/xt_hl.c
> 	modified:   net/netfilter/xt_rateest.c
> 	modified:   net/netfilter/xt_tcpmss.c
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> ```
> 
> ```
> diff --git a/include/uapi/linux/netfilter/xt_CONNMARK.h b/include/uapi/linux/netfilter/xt_CONNMARK.h
> index 2f2e48e..efc17a8 100644
> --- a/include/uapi/linux/netfilter/xt_CONNMARK.h
> +++ b/include/uapi/linux/netfilter/xt_CONNMARK.h
> @@ -1,6 +1,31 @@
> -#ifndef _XT_CONNMARK_H_target
> -#define _XT_CONNMARK_H_target
> +#ifndef _XT_CONNMARK_H
> +#define _XT_CONNMARK_H
>  
> -#include <linux/netfilter/xt_connmark.h>
> +#include <linux/types.h>
>  
> -#endif /*_XT_CONNMARK_H_target*/
> +/* Copyright (C) 2002,2004 MARA Systems AB <http://www.marasystems.com>
> + * by Henrik Nordstrom <hno@marasystems.com>
> + *
> + * This program is free software; you can redistribute it and/or modify
> + * it under the terms of the GNU General Public License as published by
> + * the Free Software Foundation; either version 2 of the License, or
> + * (at your option) any later version.
> + */
> +
> +enum {
> +       XT_CONNMARK_SET = 0,
> +       XT_CONNMARK_SAVE,
> +       XT_CONNMARK_RESTORE
> +};
> +
> +struct xt_connmark_tginfo1 {
> +       __u32 ctmark, ctmask, nfmask;
> +       __u8 mode;
> +};
> +
> +struct xt_connmark_mtinfo1 {
> +       __u32 mark, mask;
> +       __u8 invert;
> +};
> +
> +#endif /*_XT_CONNMARK_H*/
> ```
> 
> One of the few files with `git diff`

Sorry, I have no idea why this happens and how exactly you got into
this state.  What about just calling `git checkout -f'?


Corinna

**Comment by ruchern** [comment]
I just did a `git clone https://github.com/github-cygwin/android_kernel_samsung_apq8084` then followed by `git status` and I see those unstaged files.

It's weird.

**Comment by github-cygwin** [comment]
Sorry, I really don't know.  I tried it myself and a collegue of mine tried it as well with the expected result.  I'll close this issue since it's a local problem, not a generic problem with this repo.  Hope that's ok.

Corinna

**Comment by ruchern** [comment]
It's just too weird. I pulled the exact same repo on Linux Ubuntu server and the problem still persist.
